name: biometricx_example
description: Demonstrates how to use the biometricx plugin.
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  get_storage: ^2.0.3
  provider: ^5.0.0
  flutter_styled_toast: ^2.0.0
  fluttertoast: ^8.0.8
  biometricx:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true